apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: default-app-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-test-node-secret
  dataFrom:
    - extract:
        key: default/mysql-test-node-secret