cloud_name: "kubernetes"
templates:
  - name: "image-builder"
    label: "image-builder"
    container_name: "podman"
    image: "quay.io/podman/stable:latest"
    command: "sleep"
    args: "999999"
    privileged: true
    mountPath: "/var/lib/containers"