apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: example-mysql-cluster
  namespace: datastore
spec:
  clusterDef: mysql
  topology: semisync        # semi-synchronous replication: 1 primary + N candidates
  terminationPolicy: Delete
  componentSpecs:
    - name: mysql
      serviceVersion: 8.0.35
      replicas: 3            # 1 primary + 2 secondary/candidate nodes
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: '0.5'
          memory: 0.5Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: ""
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
 