apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-tls
        key: ca.crt
        namespace: vault   # ClusterSecretStore needs this explicit, since it has no inherent namespace
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-controller"